from enum import Enum


class IntentLabel(str, Enum):
    GOAL_LIST_QUERY = "GOAL_LIST_QUERY"
    IDENTITY_QUERY = "IDENTITY_QUERY"
    PERSONAL_FACT_QUERY = "PERSONAL_FACT_QUERY"
    PERSONAL_PROFILE_QUERY = "PERSONAL_PROFILE_QUERY"
    MEMORY_WRITE_REQUEST = "MEMORY_WRITE_REQUEST"
    GOAL_WRITE_REQUEST = "GOAL_WRITE_REQUEST"
    PERSONAL_ASSERTION = "PERSONAL_ASSERTION"
    GENERAL_CONVERSATION = "GENERAL_CONVERSATION"


TRAINED_LABELS = tuple(label.value for label in IntentLabel)
